name: Publish to GitHub Pages
'on':
  push:
    branches:
      - master
jobs:
  "Publish to Pages":
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node packages
        run: npm install
      - run: |
          git config user.name ${GITHUB_ACTOR}
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm run deploy
